<?php
namespace App\Exceptions;

use App\Traits\ApiJsonResponse;
use Exception;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Database\QueryException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Validation\ValidationException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Throwable;

class Handler extends ExceptionHandler
{
    use ApiJsonResponse;

    /**
     * A list of exception types with their corresponding custom log levels.
     *
     * @var array<class-string<\Throwable>, \Psr\Log\LogLevel::*>
     */
    protected $levels = [
        //
    ];

    /**
     * A list of the exception types that are not reported.
     *
     * @var array<int, class-string<\Throwable>>
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Throwable  $e
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @throws \Throwable
     */
    public function render($request, Throwable $exception)
    {
        if ($request->is('api/*')) {
            return match (true) {
                $exception instanceof AuthenticationException => $this->respondUnauthorized(),
                $exception instanceof NotFoundHttpException => $this->respondNotFound('Not Found'),
                $exception instanceof ModelNotFoundException => $this->respondNotFound('Resource Not Found'),
                $exception instanceof ValidationException => $this->respondValidationErrors($exception->validator),
                $exception instanceof QueryException => $this->respondInvalidQuery($exception->getMessage()),
                $exception instanceof Exception => $this->respondInternalError($exception->getMessage()),
            };
        }

        return parent::render($request, $exception);
    }
}
